name: Deploy Static Web App
 
on:

  push:

    branches:

      - master  # Change this if your main branch has a different name
 
jobs:

  build_and_deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v3
 
      - name: Build and Deploy

        uses: Azure/static-web-apps-deploy@v1

        with:

          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          repo_token: ${{ secrets.GITHUB_TOKEN }}

          action: "upload"

          app_location: "/"  # Change this if your files are inside a subfolder like "src"

          output_location: "."  # Change based on your build output folder

 
